### ISSUE TITLE
Float/Integer evaluation in typed langages

### ISSUE THREAD

**Issue by thomaspoignant** [open-feature/spec#115]
I was looking at the different SDKs and we don't have a feature parity concerning the number flag evaluation.

Sometimes the number method retrieves `integer` (java SDK) and others are retrieving `float`.
It could be great to be explicit in the spec about what behavior we expect.

[Reference in the specs](https://github.com/open-feature/spec/blob/main/specification/flag-evaluation.md#condition-132)

**Comment by toddbaert** [comment]
I'm hesitant to define exactly what types/bit-lengths/signs we expect, because there's so much variety across languages. I think it's best for the spec to stay vague here. What we do have is this: https://github.com/open-feature/spec/blob/main/specification/types.md#number, which we could perhaps link/reference better throughout the spec.

**Comment by thomaspoignant** [comment]
What is not clear from me is if we want to have one `getNumber` function that is generic or do we also accept to have  multiple functions such as `getInteger`, `getFloat`, etc ...

**Comment by thomaspoignant** [comment]
Resolves in #116
